name: wave_app
description: AI-Powered World Analysis & Visualization Engine
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.2
  go_router: ^16.2.1
  
  # 3D Graphics and Visualization
  webview_flutter: ^4.4.2
  vector_math: ^2.1.4
  flutter_cube: ^0.1.1
  
  # Maps and Geospatial
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  
  # Animations
  lottie: ^3.3.1
  rive: ^0.13.20
  
  # State Management
  provider: ^6.1.1
  
  # HTTP and Data
  http: ^1.1.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.5
  intl: ^0.19.0
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/


  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700