// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0AEwSFVU94zpNdyL4cGXsxKsCMN59sUk',
    appId: '1:240747642772:web:abcdef123456789',
    messagingSenderId: '240747642772',
    projectId: 'wave-dc616',
    authDomain: 'wave-dc616.firebaseapp.com',
    storageBucket: 'wave-dc616.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0AEwSFVU94zpNdyL4cGXsxKsCMN59sUk',
    appId: '1:240747642772:android:ec87bfb4d2ecba51d95981',
    messagingSenderId: '240747642772',
    projectId: 'wave-dc616',
    storageBucket: 'wave-dc616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AEwSFVU94zpNdyL4cGXsxKsCMN59sUk',
    appId: '1:240747642772:ios:abcdef123456789',
    messagingSenderId: '240747642772',
    projectId: 'wave-dc616',
    storageBucket: 'wave-dc616.firebasestorage.app',
    iosBundleId: 'com.wave.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AEwSFVU94zpNdyL4cGXsxKsCMN59sUk',
    appId: '1:240747642772:macos:abcdef123456789',
    messagingSenderId: '240747642772',
    projectId: 'wave-dc616',
    storageBucket: 'wave-dc616.firebasestorage.app',
    iosBundleId: 'com.wave.app',
  );
}